# pingTimeout = "10s"
# pingInterval = "1s"


[[ proxies ]]
name = "foo"
addr = ":8001"
# tls_cert = "abc.cert"
# tls_key = "abc.key"

# [[ proxies.backends ]]
# addr = "1.2.3.4:8000"

# [[ proxies.backends ]]
# addr = "5.6.7.8:8000"


[[ proxies ]]
name = "bar"
addr = ":8002"
# tls_cert = "abc.cert"
# tls_key = "abc.key"

# [[ proxies.backends ]]
# addr = "hello:8000"

# [[ proxies.backends ]]
# addr = "world:8000"
