# pingTimeout = "10s"
# pingInterval = "1s"
# pingReconnectInterval = "1s"


[[ proxies ]]
name = "foo"
addr = ":8100"

# [[ proxies.backends ]]
# addr = "1.2.3.4:8080"

# [[ proxies.backends ]]
# addr = "1.2.3.4:8080"

# [[ proxies.backends ]]
# addr = "1.2.3.4:8080"


# [[ proxies ]]
# name = "bar"
# addr = ":8200"

# [[ proxies.backends ]]
# addr = "1.2.3.4:8080"

# [[ proxies.backends ]]
# addr = "1.2.3.4:8080"
