pingTimeout = "10s"
pingInterval = "1s"
pingReconnectInterval = "1s"


[[ proxies ]]
name = "foo"
addr = "localhost:8100"

[[ proxies.backends ]]
addr = "localhost:8101"

[[ proxies.backends ]]
addr = "localhost:8102"


[[ proxies ]]
name = "bar"
addr = "localhost:8200"

[[ proxies.backends ]]
addr = "localhost:8201"

[[ proxies.backends ]]
addr = "localhost:8202"
